syntax = "proto3";

package gee.v1;

service ExecutionEngine {
    rpc Execute(CommandRequest)
        returns (stream CommandResponse);

    rpc ExecuteStream(stream CommandChunk)
        returns (stream CommandResponse);
}

enum CommandType {
    SQL = 0;
    FUNCTION = 1;
    PROCEDURE = 2;
}

message Parameter {
    string name = 1;

    oneof value {
        string string_value = 2;
        int64 int_value = 3;
        double double_value = 4;
        bool bool_value = 5;
        bytes bytes_value = 6;
    }
}

message CommandRequest {
    string request_id = 1;

    CommandType type = 2;

    string command = 3;

    repeated Parameter parameters = 4;
}

message CommandChunk {
    string request_id = 1;

    bytes payload = 2;
}

message CommandResponse {
    bool success = 1;

    string message = 2;

    bytes payload = 3;
}